---
abstract: "file parser intended for big files that doesn't fit into main memory."
author:
  - 'Alexis Sukrieh <sukria@sukria.net>'
build_requires:
  File::Basename: 0
  File::Spec: 0
  Test::More: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Slurp-Fast
requires:
  Carp: 0
  Encode: 0
  IO::File: 0
  Moo: 0
resources:
  bugtracker: https://github.com/Weborama/File-Slurp-Fast/issues
  homepage: https://github.com/Weborama/File-Slurp-Fast/wiki
  repository: git://github.com/Weborama/File-Slurp-Fast.git
version: 0.002
